# Generated by Django 2.1.4 on 2019-04-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('pro', models.URLField(max_length=300)),
                ('followers', models.IntegerField(default=0)),
                ('followered', models.IntegerField(default=0)),
                ('articles', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('pic', models.URLField(max_length=300)),
                ('like', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
            ],
        ),
    ]
