# Generated by Django 2.1.7 on 2019-04-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='followered',
            new_name='following',
        ),
        migrations.RemoveField(
            model_name='article',
            name='pro',
        ),
    ]
